config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :attachment, styles: { thumb: "200x200>", exploded: { processors: [:exploder] } }

  validates :title, presence: true
  validates :description, length: { maximum: 250 }, allow_blank: true
  validates_attachment_presence :attachment
  validates_attachment_content_type :attachment, :content_type => /\Aimage/
  validates_attachment_size :attachment, :in => 0.megabytes..2000.kilobytes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    photo_count = Photo.count
    @photo = Photo.offset(rand(photo_count)).first
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :attachment)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/home/index.html.slim
-if @photo
  canvas#gifAnimation data-url=(URI.join(request.url, @photo.attachment.url(:exploded))) data-imgHeight=(@photo.attachment.height) data-totalHeight=(@photo.attachment.height(:exploded)) data-imgWidth=(@photo.attachment.width)
-else
  .row
    .jumbotron
      h1 No image
      p You should upload new images.
      p
        =link_to "Add a new photo", new_photo_path, class: "btn btn-primary"

app/views/layouts/application.html.slim
doctype html
html
  head
  title Tilt Me
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  body
    nav.navbar.navbar-default role="navigation"
      .container-fluid
        .navbar-header
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-nav"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Tilt Me", :root, class: "navbar-brand"

        #top-nav.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              = link_to "Photos", :photos
    .container
      = yield

app/views/photos/index.html.slim
.row

  h1.page-header Photos
  =link_to "Add a new photo", new_photo_path, class: "btn btn-primary"
  table.table
    thead
      tr
        th #
        th Image
        th Title
        th Description
        th Actions
    tbody
      - @photos.each do |photo|
        tr
          td = photo.id
          td
            = image_tag(photo.attachment.url(:thumb), style:"height:100px")
          td = photo.title
          td = photo.description
          td
            =link_to photo_path(photo), data: { confirm: "Photo will be deleted. Are you sure?"}, method: :delete, class: "btn btn-default btn-red", title: "Delete photo"
              | Delete photo

app/views/photos/new.html.slim
.row

  h1.page-header Add new photo

  =form_for @photo, html: { multipart: true } do |f|
    - if @photo.errors.any?
      .alert.alert-danger.alert-dismissable
        button aria-hidden="true" data-dismiss="alert" class="close" type="button" ×
        ul
          - @photo.errors.full_messages.each do |msg|
            li = msg
    .form-group
      button type="button" class="btn btn-default js-choose-photo-attachment-button"
        i.fa.fa-paperclip
        span  Choose File...
      | &nbsp;
      span.file_name.js-attachment-filename  File name...
      = f.file_field :attachment, class: "js-photo-attachment-input hidden"
      .light The maximum file size allowed is 2MB.
    .form-group
      = f.label :title
      = f.text_field :title, :autofocus => true, 'placeholder' => "Enter photo title", class: "form-control"
    .form-group
      = f.label :description
      = f.text_area :description, rows: "6", 'placeholder' => "Describe a little more this photo.", class: "form-control"

    button.btn.btn-primary.pull-right type="submit" Submit